### PR TITLE
feat(tools/jupyter): provide completions for Jupyter kernel

### PR DESCRIPTION
**Pull request by rgbkrk**
An initial completions implementation for a `complete_request`.

### CODE REVIEW

**Comment by bartlomieju** [comment]
@rgbkrk I'll provide you with some hint how you can use actual completions coming from the LSP later tonight.

**Comment by bartlomieju** [comment]
@rgbkrk actually I think you have all the things you need are already available - we don't need to use `ReplEditor` - the actual completions are provided by the `ReplSession.language_server`. You can get them by calling `ReplSession.language_server.completions` by providing the source line and "position" where position is byte offset from the start of the line. You'll get back a list of "ReplCompletionItem" which contains suggested completion text and range of the source code that it applies to. 

Let me know if that's enough to unblock you

**Comment by rgbkrk** [comment]
Ah! Fantastic. This is plenty, thank you. I'll give it a shot.

**Comment by rgbkrk** [comment]
I'm never getting any elements in the `completions` response when I would expect to, so I'll have to do some more digging

```
CODE: "console."
CURSOR POS: 8
COMPLETIONS: []
MATCHES: []
```

**Comment by bartlomieju** [comment]
@rgbkrk strange, but I just tried with the `deno repl` and typing `console.` doesn't yield any suggestions either! Do you get any suggestions if you do `Deno.`?

**Comment by bartlomieju** [comment]
Yikes, my mistake again! I just tried with the REPL and indeed the completions are not actually coming from the LSP, but rather from other machinery defined in `cli/tools/repl/editor.rs::EditorHelper` (namely `get_expr_from_lint_at_pos` and friends. I think we could abstract that whole logic into a helper function in the `cli/tools/repl/editor.rs` and make it public so we can reuse it in the kernel (alternatively just copy-paste relevant code for now, we can dedup it in a followup). Let me know if you want to try and tackle that or should I do it.

**Comment by rgbkrk** [comment]
No suggestions with `Deno.` either.

However, if I run some debug statements inside of the `completions` implementation of `cli/lsp/repl.rs` then I see that the completions response from the private `language_server` is non-empty (and with the data I expect).

**Comment by rgbkrk** [comment]
> Yikes, my mistake again! I just tried with the REPL and indeed the completions are not actually coming from the LSP, but rather from other machinery defined in `cli/tools/repl/editor.rs::EditorHelper` (namely `get_expr_from_lint_at_pos` and friends. I think we could abstract that whole logic into a helper function in the `cli/tools/repl/editor.rs` and make it public so we can reuse it in the kernel (alternatively just copy-paste relevant code for now, we can dedup it in a followup). Let me know if you want to try and tackle that or should I do it.

All good. Just happy to learn over here.

Given the level of involvement to add that on and my complete new-ness to Rust, I'd love if you tackle it so I can read the commits and learn.

**Comment by bartlomieju** [comment]
@rgbkrk this is now done and works nicely (<s>but cursor_start/cursor_end need to be tweaked</s>) :) however there's a ton of spam regarding `inspect_request`. Should we implement that one as well?

**Comment by bartlomieju** [comment]
I'm thinking that `inspect_request` could use `deno doc` or the LSP machinery to show markdown docs for the functions, but I'll be happy to do that in a follow up.

**Comment by rgbkrk** [comment]
Sweet! Might as well put in inspect request. LSP definitely has it all.

**Comment by bartlomieju** [comment]
@rgbkrk are you fine to land this as is?

**Comment by rgbkrk** [comment]
On a side note wow are my messages delayed when using GitHub on mobile.

> @rgbkrk are you fine to land this as is?

Sounds good to me.

**Comment by rgbkrk** [comment]
Looks like `Deno.`-tab completes while `console.` does not. Fine for now though. This is materially better than the previous behavior of crashing. It works with variables defined in previous cells so this is solid interactive completion. If I had to guess, it's a native v8 thing that we'd have to put on the base repl. Amusingly if you do something silly like this:

```
var con = console
```

then you can tab complete `con`:

image

**Comment by bartlomieju** [comment]
> Looks like `Deno.`-tab completes while `console.` does not. Fine for now though. This is materially better than the previous behavior of crashing. It works with variables defined in previous cells so this is solid interactive completion. If I had to guess, it's a native v8 thing that we'd have to put on the base repl. Amusingly if you do something silly like this:
> 
> ```
> var con = console
> ```
> 
> then you can tab complete `con`:
> 
> image

I think this is either a limitation of Deno's REPL or a bug. Could you convert this comment to an issue in the Deno repo? We should be able to figure out that `console` is available on the global scope.

**Comment by rgbkrk** [comment]
> Could you convert this comment to an issue in the Deno repo?

Yep. It's now https://github.com/denoland/deno/issues/20442

**Pull request merged**
